"""Added post table

Revision ID: 71691d15eff0
Revises: fcb75964c07f
Create Date: 2021-08-04 14:44:03.285742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71691d15eff0'
down_revision = 'fcb75964c07f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('body', sa.String(length=225), nullable=True),
    sa.Column('data_created', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    # ### end Alembic commands ###
